### ISSUE TITLE
Encrypted data and Eloquent

### ISSUE THREAD

**Issue by matthewmerendo** [Cheezykins/LaravelEncryptable#3]
Is there a way to use encrypted data in an Eloquent retrieval? For instance, I'm doing a firstOrCreate based on a first name, last name, and encrypted birthdate -- but it seems not to work, presumably because the database birthdate is encrypted and the value it's trying to match is not.

**Comment by Cheezykins** [comment]
Unfortunately not.

As you say it's because it tries to match the date you provide against an encrypted value and so doesn't find a match, It would have to read all the dates of birth out of the database and decrypt them before it could match against them.

Because the initialisation vector is random each time (and has to be for the AES-CBC mode to be secure) the encryption method is non-deterministic and two given dates don't give the same output, this means you cannot just encrypt the input date of birth and compare the ciphertexts.
